import { Branch, Language } from './types';

export const BRANCHES: Branch[] = [
  {
    id: 'branch-rustaveli',
    name_uz: 'Yalpiz — Shota Rustaveli 115',
    name_ru: 'Yalpiz — Шота Руставели, 115',
    address_uz: 'Toshkent sh., Shota Rustaveli ko‘chasi, 115-uy',
    address_ru: 'г. Ташкент, ул. Шота Руставели, д. 115',
    hours_uz: 'Har kuni 10:00–00:00',
    hours_ru: 'Ежедневно 10:00–00:00',
    phone: '+998 95 193 98 98',
    phoneRaw: '+998951939898',
    mapEmbedUrl: 'https://maps.google.com/maps?q=41.2616693,69.2278536&z=17&output=embed',
    mapUrl: 'https://maps.app.goo.gl/gqtPmmVPRRTcLWCv9',
  },
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  uz: {
    // Nav & General UI
    brandName: 'Yalpiz',
    brandSlogan: 'Milliy va Zamonaviy Ta’m',
    navMenu: 'Menyu',
    navPromo: 'Joy band qilish',
    navAbout: 'Biz haqimizda',
    navBranches: 'Manzil',
    navContact: 'Aloqa',
    orderBtn: 'Buyurtma berish',
    searchPlaceholder: 'Taomlarni qidirish...',
    popularBadge: 'Ommabop',
    currency: 'so‘m',
    available: 'Mavjud',
    outOfStock: 'Tugagan',
    addToCart: 'Savatga qo‘shish',
    cart: 'Savat',
    promoTitle: 'Aksiyalar va Maxsus Takliflar',
    promoSub: 'Yalpizdan eng mazali chegirmalar va to‘plamlar',
    reviewsTitle: 'Mijozlarimiz fikri',
    reviewsSub: 'Yalpiz mehmondo‘stligi va taomlarining haqiqiy bahosi',
    exploreMenu: 'Menyuni ko‘rish',
    learnMore: 'Batafsil',

    // Hero Section
    heroTitle: 'Milliy taomlar — eshigingizgacha',
    heroSub: 'An’anaviy retseptlar, yangi mahsulotlar va professional oshpazlar mahorati. Toshkent bo‘ylab yetkazib berish va olib ketish xizmati.',
    marqueeFreeDelivery: 'Tez va ishonchli yetkazamiz',
    marqueeFreshDishes: 'Yangi yopilgan issiq nonlar',
    marqueeHotAndFresh: 'Issiq va sersuv kaboblar',
    marqueeTgOrder: 'Sayt orqali qulay buyurtma',
    marqueeTradition: 'Asliy milliy ta’m',

    // Value Strip "Nega Yalpiz"
    whyTitle: 'Nega aynan Yalpiz?',
    whySub: 'Biz har bir taomni mehr bilan, milliy an’analarimiz va gigiyena qoidalariga rioya qilgan holda tayyorlaymiz',
    whyFreshTitle: '100% Yangi Mahsulotlar',
    whyFreshDesc: 'Har tong sarxil va tekshirilgan go‘sht va sabzavotlar tanlab olinadi.',
    whyFastTitle: 'Tezkor Yetkazib Berish',
    whyFastDesc: 'Maxsus termosumkalar yordamida taomlar issiq va o‘z ta’mida yetadi.',
    whyTasteTitle: 'Haqiqiy Milliy Lazzat',
    whyTasteDesc: 'Avloddan-avlodga o‘tib kelayotgan haqiqiy o‘zbekcha o‘tin oshi ta’mi.',
    whyAppTitle: 'Qulay Buyurtma Berish',
    whyAppDesc: 'Menyudan tanlang, savatga qo‘shing va saytda qulay buyurtma bering.',

    // Category Selector
    cat_all: 'Barchasi',
    cat_osh: 'Osh va Palovlar',
    cat_mangal: 'Mangal va Shashliklar',
    cat_salatlar: 'Salatlar va Non',
    cat_ichimliklar: 'Yalpizli Ichimliklar',
    cat_setlar: 'Maxsus To‘plamlar (Set)',

    // About Section
    aboutTitle: 'Yalpiz — samimiy mehmondo‘stlik va milliy ta’m',
    aboutP1: '"Yalpiz" — Toshkentdagi oilaviy restoran bo‘lib, o‘zbek xalqining ko‘p asrlik mehmondo‘stlik madaniyatini zamonaviy talablar bilan uyg‘unlashtiradi. Restoran nomi xushbo‘y yalpiz sharafiga qo‘yilgan — u dasturxonimizning yengillik va tozalik timsolidir.',
    aboutP2: 'Menyuimiz boy va rang-barang: an’anaviy palov, sersuv shashlik va kaboblar, lag‘mon, tansiq salatlar hamda issiq tandir non. Portsiyalarimiz to‘kin, narxlarimiz esa hamyonbop — har bir mehmon to‘yib va mamnun qaytadi.',
    aboutP3: 'Har bir mehmonni iliq kutib olamiz. Yalpiz tug‘ilgan kun, nikoh, banket va boshqa tadbirlar uchun qulay tanlov. Toshkent shahri, Shota Rustaveli ko‘chasi 115-uydagi restoranimiz har kuni sizni kutadi.',

    // Branches
    branchesTitle: 'Yalpiz restorani manzili',
    branchesSub: 'Shota Rustaveli 115-uydagi restoranimizga tashrif buyuring yoki olib ketish uchun buyurtma bering',
    branchHours: 'Ish vaqti',
    branchPhone: 'Telefon',
    branchAddress: 'Manzil',
    branchDirections: 'Xaritadan ko‘rish',

    // Delivery Section
    deliveryTitle: 'Yetkazib berish va To‘lov',
    deliverySub: 'Sizga qulay va tezkor xizmat ko‘rsatish tizimimiz bilan tanishing',
    step1Title: 'Taomlarni tanlang',
    step1Desc: 'Menyudan xohlagan shoxona taomlarimizni savatga qo‘shing va tasdiqlang.',
    step2Title: 'Manzil va ma’lumotlar',
    step2Desc: 'Yetkazib berish manzilini kiriting yoki o‘zingizga qulay filialni tanlang.',
    step3Title: 'Issiqqina qabul qiling',
    step3Desc: 'Buyurtmangiz holatiga qarab taomlar issiq holda ko‘rsatilgan manzilga yetkaziladi.',
    paymentTitle: 'To‘lov usullari',
    paymentDesc: 'Siz buyurtmani o‘zingizga qulay tarzda to‘lashingiz mumkin:',
    payme: 'Payme orqali onlayn',
    click: 'Click orqali onlayn',
    cash: 'Naqd — faqat olib ketishda',

    // Cart Drawer & Checkout
    cartTitle: 'Sizning savatingiz',
    cartEmpty: 'Savatingiz hozircha bo‘sh. Yoqimli taomlardan buyurtma bering!',
    cartSummary: 'Buyurtma tafsilotlari',
    cartTotal: 'Jami summa:',
    cartDeliveryCost: 'Yetkazib berish:',
    cartFree: 'Taxi haydovchiga naqd',
    checkoutTitle: 'Buyurtmani rasmiylashtirish',
    orderType: 'Buyurtma turi',
    typeDelivery: 'Yetkazib berish (Dostavka)',
    typePickup: 'Olib ketish (Samovivoz)',
    fullName: 'Ismingiz va familiyangiz',
    fullNamePlaceholder: 'Masalan: Alisher Karimov',
    phoneLabel: 'Telefon raqamingiz',
    phonePlaceholder: '99 123 45 67',
    addressLabel: 'Yetkazib berish manzili',
    addressPlaceholder: 'Tuman, ko‘cha, uy raqami, xonadon',
    selectBranch: 'Olib ketish filialini tanlang',
    paymentMethod: 'To‘lov turi',
    commentLabel: 'Kuryer yoki oshpaz uchun eslatma (ixtiyoriy)',
    commentPlaceholder: 'Masalan: Kirish kodi 45, oshga piyoz ko‘proq bo‘lsin',
    submitOrder: 'Buyurtmani tasdiqlash',
    orderProcessing: 'Buyurtma rasmiylashtirilmoqda...',
    orderSuccess: 'Sizning buyurtmangiz muvaffaqiyatli qabul qilindi!',
    orderSuccessSub: 'Tez orada operatorimiz siz bilan bog‘lanadi. Buyurtma raqamingiz: #YALPIZ-',
    backToMenu: 'Menyuga qaytish',
    qty: 'Soni',

    // Footer
    footerSlogan: 'O‘zbek milliy oshxonasining eng sara an’analari zamonaviy ko‘rinishda.',
    footerHours: 'Ish vaqti: Har kuni 10:00 dan 00:00 gacha',
    footerSocials: 'Biz ijtimoiy tarmoqlarda',
    footerBot: 'Naqd olib ketish buyurtmasini Telegram orqali xavfsiz tasdiqlang',
    footerApp: 'Tez kunda Google Play va App Store platformalarida',
    footerRights: 'Barcha huquqlar himoyalangan.',
  },
  ru: {
    // Nav & General UI
    brandName: 'Yalpiz',
    brandSlogan: 'Национальный и современный вкус',
    navMenu: 'Меню',
    navPromo: 'Бронирование',
    navAbout: 'О нас',
    navBranches: 'Адрес',
    navContact: 'Контакты',
    orderBtn: 'Заказать сейчас',
    searchPlaceholder: 'Поиск блюд...',
    popularBadge: 'Популярно',
    currency: 'сум',
    available: 'В наличии',
    outOfStock: 'Закончилось',
    addToCart: 'В корзину',
    cart: 'Корзина',
    promoTitle: 'Акции и Специальные Предложения',
    promoSub: 'Самые вкусные скидки и праздничные наборы от Yalpiz',
    reviewsTitle: 'Отзывы наших гостей',
    reviewsSub: 'Искренние слова о гостеприимстве и непревзойденном вкусе',
    exploreMenu: 'Смотреть меню',
    learnMore: 'Подробнее',

    // Hero Section
    heroTitle: 'Национальные блюда — прямо к вам домой',
    heroSub: 'Традиционные рецепты, свежие продукты и мастерство поваров. Доставка по Ташкенту и удобный самовывоз.',
    marqueeFreeDelivery: 'Быстрая и надёжная доставка',
    marqueeFreshDishes: 'Горячие лепешки из тандыра',
    marqueeHotAndFresh: 'Горячие сочные шашлыки',
    marqueeTgOrder: 'Удобный заказ на сайте',
    marqueeTradition: 'Оригинальный узбекский вкус',

    // Value Strip "Nega Yalpiz"
    whyTitle: 'Почему именно Yalpiz?',
    whySub: 'Мы готовим каждое блюдо с душой, строго следуя национальным традициям и стандартам гигиены',
    whyFreshTitle: '100% Свежие Продукты',
    whyFreshDesc: 'Каждое утро мы отбираем сертифицированное мясо и лучшие спелые овощи.',
    whyFastTitle: 'Быстрая Доставка',
    whyFastDesc: 'Специальные термосумки сохраняют идеальную температуру и аромат блюд.',
    whyTasteTitle: 'Аутентичный Вкус',
    whyTasteDesc: 'Настоящий плов на дровах по рецептам, передаваемым из поколения в поколение.',
    whyAppTitle: 'Удобный Заказ',
    whyAppDesc: 'Выберите блюда, добавьте в корзину и удобно оформите заказ на сайте.',

    // Category Selector
    cat_all: 'Все блюда',
    cat_osh: 'Плов и Рис',
    cat_mangal: 'Мангал и Шашлыки',
    cat_salatlar: 'Салаты и Лепешки',
    cat_ichimliklar: 'Мятные Напитки',
    cat_setlar: 'Специальные Сеты',

    // About Section
    aboutTitle: 'Yalpiz — искреннее гостеприимство и национальный вкус',
    aboutP1: '«Yalpiz» — семейный ресторан в Ташкенте, объединяющий многовековую культуру узбекского гостеприимства с современными стандартами. Название происходит от ароматной мяты — символа свежести и лёгкости нашего дастархана.',
    aboutP2: 'Наше меню богато и разнообразно: традиционный плов, сочные шашлыки и кебабы, лагман, свежие салаты и горячие тандырные лепёшки. Порции щедрые, а цены доступные — каждый гость уходит сытым и довольным.',
    aboutP3: 'В Yalpiz ценят семейное тепло и искреннюю заботу. Ресторан подходит для дней рождения, свадеб, банкетов и других мероприятий. Мы ждём вас в Ташкенте по адресу: улица Шота Руставели, 115.',

    // Branches
    branchesTitle: 'Адрес ресторана Yalpiz',
    branchesSub: 'Посетите ресторан на Шота Руставели, 115 или оформите заказ навынос',
    branchHours: 'Режим работы',
    branchPhone: 'Телефон',
    branchAddress: 'Адрес',
    branchDirections: 'Открыть на карте',

    // Delivery Section
    deliveryTitle: 'Доставка и Оплата',
    deliverySub: 'Ознакомьтесь с нашей удобной и быстрой системой сервиса',
    step1Title: 'Выберите блюда',
    step1Desc: 'Добавьте понравившиеся блюда из нашего меню в корзину и перейдите к оформлению.',
    step2Title: 'Укажите детали',
    step2Desc: 'Введите адрес доставки или выберите удобный для вас филиал самовывоза.',
    step3Title: 'Получите горячим',
    step3Desc: 'В зависимости от условий заказа блюда будут доставлены горячими по указанному адресу.',
    paymentTitle: 'Способы оплаты',
    paymentDesc: 'Вы можете оплатить свой заказ любым удобным для вас способом:',
    payme: 'Онлайн через Payme',
    click: 'Онлайн через Click',
    cash: 'Наличные — только при самовывозе',

    // Cart Drawer & Checkout
    cartTitle: 'Ваша корзина',
    cartEmpty: 'Ваша корзина пуста. Добавьте в нее наши вкуснейшие блюда!',
    cartSummary: 'Детали заказа',
    cartTotal: 'Итоговая сумма:',
    cartDeliveryCost: 'Доставка:',
    cartFree: 'Такси водителю наличными',
    checkoutTitle: 'Оформление заказа',
    orderType: 'Способ получения',
    typeDelivery: 'Доставка на дом',
    typePickup: 'Самовывоз из филиала',
    fullName: 'Ваше имя и фамилия',
    fullNamePlaceholder: 'Например: Алишер Каримов',
    phoneLabel: 'Номер телефона',
    phonePlaceholder: '99 123 45 67',
    addressLabel: 'Адрес доставки',
    addressPlaceholder: 'Район, улица, номер дома, квартира',
    selectBranch: 'Выберите филиал для самовывоза',
    paymentMethod: 'Способ оплаты',
    commentLabel: 'Комментарий к заказу (необязательно)',
    commentPlaceholder: 'Например: Вход со двора, код домофона 45, плов без лука',
    submitOrder: 'Подтвердить заказ',
    orderProcessing: 'Оформление заказа...',
    orderSuccess: 'Ваш заказ успешно принят!',
    orderSuccessSub: 'В ближайшее время с вами свяжется оператор для подтверждения. Номер вашего заказа: #YALPIZ-',
    backToMenu: 'Вернуться в меню',
    qty: 'Кол-во',

    // Footer
    footerSlogan: 'Лучшие традиции узбекской национальной кухни в современном и стильном исполнении.',
    footerHours: 'Время работы: Ежедневно с 10:00 до 00:00',
    footerSocials: 'Мы в социальных сетях',
    footerBot: 'Безопасно подтверждайте наличный самовывоз через Telegram',
    footerApp: 'Скоро в Google Play и App Store',
    footerRights: 'Все права защищены.',
  }
};
