import { MenuItem, Promo, Branch, Testimonial, Language } from './types';

export const MENU_ITEMS: MenuItem[] = [
  {
    id: 'osh-traditional',
    name_uz: 'Yalpiz Shoxona Oshi',
    name_ru: 'Плов Шахский Yalpiz',
    desc_uz: 'Tandirda pishirilgan qo‘y go‘shti, eng saralangan dumsiz guruch, shirin sabzi va maxsus ziravorlar bilan haqiqiy o‘zbek oshi.',
    desc_ru: 'Настоящий узбекский плов из отборного риса лазер, нежной баранины из тандыра, сладкой моркови и ароматных специй.',
    price: 35000,
    category: 'osh',
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?q=80&w=600&auto=format&fit=crop',
    available: true,
    isPopular: true,
    badge_uz: 'Eng xaridorbop',
    badge_ru: 'Хит продаж',
    prepTime_uz: '20-25 daqiqa',
    prepTime_ru: '20-25 минут',
  },
  {
    id: 'osh-toy',
    name_uz: 'Toshkent To‘y Oshi',
    name_ru: 'Ташкентский Свадебный Плов',
    desc_uz: 'Nuxat, mayiz, bedana tuxumi va ot go‘shtidan tayyorlangan qazi bilan bezatilgan tantanavor to‘y oshi.',
    desc_ru: 'Праздничный плов с нутом, изюмом, перепелиными яйцами и деликатесной казы из конины.',
    price: 40000,
    category: 'osh',
    image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?q=80&w=600&auto=format&fit=crop',
    available: true,
    badge_uz: 'An’anaviy',
    badge_ru: 'Традиционный',
    prepTime_uz: '15-20 daqiqa',
    prepTime_ru: '15-20 минут',
  },
  {
    id: 'osh-choyxona',
    name_uz: 'Choyxona Oshi (Qalampir bilan)',
    name_ru: 'Чайханский Плов (с перцем)',
    desc_uz: 'To‘q rangli guruch va qovurilgan dumba yog‘ida tayyorlangan, achchiq garmdorili erkaklarbop to‘yimli osh.',
    desc_ru: 'Тёмный, насыщенный чайханский плов на курдючном жире с чесноком и пикантным острым перцем.',
    price: 38000,
    category: 'osh',
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?q=80&w=600&auto=format&fit=crop',
    available: true,
    prepTime_uz: '20-30 daqiqa',
    prepTime_ru: '20-30 минут',
  },
  {
    id: 'mangal-assorti',
    name_uz: 'Yalpiz Mangal Assortisi',
    name_ru: 'Мангал Ассорти Yalpiz',
    desc_uz: 'Qo‘y go‘shti va tovuq kaboblari, jaz va qiymali shashliklar to‘plami. Piyoz va maxsus pomidor sousi bilan tortiladi.',
    desc_ru: 'Большое плато шашлыков: нежная баранина, куриные крылышки, люля-кебаб и сочный джаз. Подается с луком и фирменным томатным соусом.',
    price: 75000,
    category: 'mangal',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?q=80&w=600&auto=format&fit=crop',
    available: true,
    isPopular: true,
    badge_uz: 'Kompaniya uchun',
    badge_ru: 'Для компании',
    prepTime_uz: '30-40 daqiqa',
    prepTime_ru: '30-40 минут',
  },
  {
    id: 'mangal-tovuq',
    name_uz: 'Tovuq go‘shtidan kabob',
    name_ru: 'Шашлык из куриного филе',
    desc_uz: 'Yalpiz va limon sousida marinadlangan, ko‘mirlarda mayin pishirilgan tovuq go‘shti shashligi.',
    desc_ru: 'Нежное куриное филе, маринованное в фирменном соусе с мятой и лимоном, запеченное на углях.',
    price: 28000,
    category: 'mangal',
    image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?q=80&w=600&auto=format&fit=crop',
    available: true,
    prepTime_uz: '25-30 daqiqa',
    prepTime_ru: '25-30 минут',
  },
  {
    id: 'mangal-qiymali',
    name_uz: 'Qiymali Kabob (Lyulya)',
    name_ru: 'Люля-Кебаб из говядины',
    desc_uz: 'Maydalangan mol va dumba go‘shtidan olovda pishirilgan, sersuv va og‘izda eriydigan kabob.',
    desc_ru: 'Сочный люля-кебаб из рубленой говядины с добавлением курдючного жира и восточных специй.',
    price: 30000,
    category: 'mangal',
    image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?q=80&w=600&auto=format&fit=crop',
    available: true,
    prepTime_uz: '20-25 daqiqa',
    prepTime_ru: '20-25 минут',
  },
  {
    id: 'mangal-quzi',
    name_uz: 'Qo‘y qovurg‘alaridan kabob',
    name_ru: 'Шашлык из каре ягненка',
    desc_uz: 'Ko‘mir ta’mi va ziravorlar bilan to‘yingan, eng mayin qo‘y qovurg‘alari.',
    desc_ru: 'Отборные ребрышки молодого ягненка на углях с хрустящей корочкой и сочной серединкой.',
    price: 55000,
    category: 'mangal',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=600&auto=format&fit=crop',
    available: true,
    badge_uz: 'Gurman',
    badge_ru: 'Гурман',
    prepTime_uz: '30-35 daqiqa',
    prepTime_ru: '30-35 минут',
  },
  {
    id: 'salat-achichuk',
    name_uz: 'Haqiqiy Achichuk',
    name_ru: 'Ачичук Классический',
    desc_uz: 'Yupqa to‘g‘ralgan sersuv pomidor, achchiq piyoz, qalampir va rayhon barglari bilan tayyorlangan milliy salat.',
    desc_ru: 'Тончайшие слайсы спелых помидоров, острый фиолетовый лук, свежий базилик и перец стручковый. Идеально к плову.',
    price: 15000,
    category: 'salatlar',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=600&auto=format&fit=crop',
    available: true,
    prepTime_uz: '5-10 daqiqa',
    prepTime_ru: '5-10 минут',
  },
  {
    id: 'salat-bahor',
    name_uz: 'Bahor Salati',
    name_ru: 'Салат Бахор',
    desc_uz: 'Yangi bodring, rediska, ko‘katlar va o‘simlik yog‘i qo‘shilgan yengil bahoriy salat.',
    desc_ru: 'Легкий весенний салат из свежих огурцов, редиса, молодой зелени и заправки на растительном масле.',
    price: 16000,
    category: 'salatlar',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?q=80&w=600&auto=format&fit=crop',
    available: true,
    prepTime_uz: '5-10 daqiqa',
    prepTime_ru: '5-10 минут',
  },
  {
    id: 'salat-suzma',
    name_uz: 'Chakka (Suzma ko‘katli)',
    name_ru: 'Сузьма с зеленью',
    desc_uz: 'Yalpiz va kashnich qo‘shilgan nordon sutli milliy chakka, taomlar hazm bo‘lishini osonlashtiradi.',
    desc_ru: 'Традиционная кисломолочная сузьма со свежей мятой, укропом и кинзой. Отлично дополняет мясные блюда.',
    price: 12000,
    category: 'salatlar',
    image: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?q=80&w=600&auto=format&fit=crop',
    available: true,
    prepTime_uz: '5-10 daqiqa',
    prepTime_ru: '5-10 минут',
  },
  {
    id: 'non-tandir',
    name_uz: 'Tandir Issiq Non',
    name_ru: 'Лепешка из тандыра',
    desc_uz: 'Sut va sariyog‘ qo‘shib o‘tin pechida yopilgan, usti kunjutli issiq va qarsillaydigan non.',
    desc_ru: 'Горячая пышная лепешка с кунжутом, испеченная в глиняном тандыре на дровах по старинному рецепту.',
    price: 6000,
    category: 'salatlar', // We group bread under salatlar for simplicity or call it milliy salatlar/non
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=600&auto=format&fit=crop',
    available: true,
    badge_uz: 'Yangi yopilgan',
    badge_ru: 'Из печи',
    prepTime_uz: '5 daqiqa',
    prepTime_ru: '5 минут',
  },
  {
    id: 'drink-yalpiz',
    name_uz: 'Yalpizli Muzdek Limonad',
    name_ru: 'Фирменный Мятный Лимонад',
    desc_uz: 'Yangi yalpiz barglari, limon va laym sharbati hamda tabiiy sirop qo‘shib tayyorlangan muzdek limonad.',
    desc_ru: 'Освежающий напиток из свежих листьев мяты, сока лимона, лайма и натурального мятного сиропа со льдом.',
    price: 18000,
    category: 'ichimliklar',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=80&w=600&auto=format&fit=crop',
    available: true,
    isPopular: true,
    badge_uz: 'Yalpiz hidi',
    badge_ru: 'Аромат мяты',
    prepTime_uz: '5-10 daqiqa',
    prepTime_ru: '5-10 минут',
  },
  {
    id: 'drink-kokchoy',
    name_uz: 'Ko‘k Choy Choynakda',
    name_ru: 'Чайник Зеленого Чая',
    desc_uz: 'Yalpiz va limon bo‘laklari bilan damlangan klassik 95 ko‘k choy, milliy piyolalar bilan birga.',
    desc_ru: 'Классический узбекский зеленый чай №95 со свежей мятой и долькой лимона. Подается в чайнике с пиалами.',
    price: 8000,
    category: 'ichimliklar',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=600&auto=format&fit=crop',
    available: true,
    prepTime_uz: '5 daqiqa',
    prepTime_ru: '5 минут',
  },
  {
    id: 'drink-rayhon',
    name_uz: 'Rayhonli Sharbat',
    name_ru: 'Базиликовый напиток',
    desc_uz: 'Qizil rayhon barglari va limon kislotasi qo‘shilgan, o‘ziga xos yoqimli nordon ta’mli ichimlik.',
    desc_ru: 'Традиционный узбекский настой из красного базилика с лимоном, обладающий глубоким цветом и тонким вкусом.',
    price: 18000,
    category: 'ichimliklar',
    image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?q=80&w=600&auto=format&fit=crop',
    available: true,
    prepTime_uz: '5-10 daqiqa',
    prepTime_ru: '5-10 минут',
  },
  {
    id: 'set-oilaviy',
    name_uz: 'Oilaviy To‘kin Dasturxon (6 kishi)',
    name_ru: 'Семейный Сет (на 6 персон)',
    desc_uz: '2 kg Yalpiz Shoxona oshi, 6 ta shashlik (aralash), 3 ta Achichuk, 2 ta issiq non, 3 ta choynak choy yoki limonad.',
    desc_ru: 'Большое застолье: 2 кг плова Шахский, 6 шампуров шашлыка, 3 порции Ачичука, 2 лепешки, чайники чая или графины лимонада.',
    price: 250000,
    category: 'setlar',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=600&auto=format&fit=crop',
    available: true,
    isPopular: true,
    badge_uz: '-15% CHEGIRMA',
    badge_ru: '-15% СКИДКА',
    prepTime_uz: '40-50 daqiqa',
    prepTime_ru: '40-50 минут',
  },
  {
    id: 'set-shoxona',
    name_uz: 'Shoxona Kabob To‘plami (4 kishi)',
    name_ru: 'Царский Сет Кабобов (на 4 персоны)',
    desc_uz: '8 dona turli xil go‘sht kaboblari (jaz, tovuq, rib, qiymali), qovurilgan kartoshka garniri, piyoz va 2 ta yangi non.',
    desc_ru: '8 премиальных шампуров шашлыка (баранина, крылышки, каре ягненка, люля), запеченный картофель, лук и 2 горячие лепешки.',
    price: 180000,
    category: 'setlar',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=600&auto=format&fit=crop',
    available: true,
    prepTime_uz: '30-40 daqiqa',
    prepTime_ru: '30-40 минут',
  }
];

export const PROMOS: Promo[] = [
  {
    id: 'promo-1',
    title_uz: 'Birinchi buyurtmaga 10% chegirma!',
    title_ru: 'Скидка 10% на первый заказ!',
    desc_uz: 'Mobil ilova yoki sayt orqali birinchi marta ro‘yxatdan o‘tib buyurtma bering va chegirmaga ega bo‘ling.',
    desc_ru: 'Зарегистрируйтесь на сайте или оформите первый заказ онлайн и получите приятную приветственную скидку.',
    badge_uz: 'XUSH KELIBSIZ',
    badge_ru: 'ДОБРО ПОЖАЛОВАТЬ',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=600&auto=format&fit=crop',
    categoryLink: 'osh'
  },
  {
    id: 'promo-2',
    title_uz: 'Oilaviy marosimlar va to‘ylar uchun setlar!',
    title_ru: 'Наборы для семейных торжеств!',
    desc_uz: 'Katta kompaniya bo‘lib buyurtma berish qulayroq. "Oilaviy set" bilan 15% gacha mablag‘ingizni tejang.',
    desc_ru: 'Заказывать сетами намного выгоднее для больших компаний. Сэкономьте до 15% с нашими сытными комбо.',
    badge_uz: 'OILAVIY AKSIYA',
    badge_ru: 'СЕМЕЙНАЯ АКЦИЯ',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=600&auto=format&fit=crop',
    price: 250000,
    categoryLink: 'setlar'
  }
];

export const BRANCHES: Branch[] = [
  {
    id: 'branch-mirobod',
    name_uz: 'Yalpiz — Mirobod filiali',
    name_ru: 'Yalpiz — Филиал Миробод',
    address_uz: 'Toshkent sh., Mirobod ko‘chasi, 5-uy',
    address_ru: 'г. Ташкент, ул. Миробод, д. 5',
    hours_uz: 'Har kuni 10:00 - 00:00',
    hours_ru: 'Ежедневно 10:00 - 00:00',
    phone: '+998 33 335 00 11',
    phoneRaw: '+998333350011',
    mapEmbedUrl: 'https://maps.google.com/maps?q=41.302113,69.266892&z=16&output=embed',
    mapUrl: 'https://yandex.uz/maps/-/CTuTY00P',
  },
  {
    id: 'branch-rustaveli',
    name_uz: 'Yalpiz — Shota Rustaveli filiali',
    name_ru: 'Yalpiz — Филиал Шота Руставели',
    address_uz: 'Toshkent sh., Shota Rustaveli ko‘chasi, 115-uy',
    address_ru: 'г. Ташкент, ул. Шота Руставели, д. 115',
    hours_uz: 'Har kuni 10:00 - 00:00',
    hours_ru: 'Ежедневно 10:00 - 00:00',
    phone: '+998 95 193 98 98',
    phoneRaw: '+998951939898',
    mapEmbedUrl: 'https://maps.google.com/maps?q=41.261786,69.227980&z=16&output=embed',
    mapUrl: 'https://yandex.uz/maps/-/CTuTYQ~M',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'review-1',
    name: 'Abdurahmon Karimov',
    role_uz: 'Tadbirkor',
    role_ru: 'Предприниматель',
    comment_uz: 'Yalpiz oshi juda lazzatli. Go‘shti og‘izda eriydi, guruchlari esa don-don bo‘lib pishgan. Tez yetkazib berishdi, rahmat!',
    comment_ru: 'Плов от Yalpiz просто великолепен. Мясо тает во рту, рисинка к рисинке. Доставили горячим и очень быстро, спасибо!',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150&auto=format&fit=crop'
  },
  {
    id: 'review-2',
    name: 'Nargiza G‘ofurova',
    role_uz: 'Dizayner',
    role_ru: 'Дизайнер',
    comment_uz: 'Menga ularning tovuqli shashliklari va yalpizli limonadlari juda yoqadi. O‘zbek milliy taomlarini shunday zamonaviy brend ostida ko‘rish ajoyib.',
    comment_ru: 'Обожаю их куриный шашлык и фирменный мятный лимонад. Приятно видеть узбекскую кухню в таком стильном и современном оформлении.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=150&auto=format&fit=crop'
  },
  {
    id: 'review-3',
    name: 'Farhod Aliyev',
    role_uz: 'Dasturchi',
    role_ru: 'Программист',
    comment_uz: 'Ajoyib sayt! Buyurtma berish jarayoni juda oson va tushunarli. Mangal to‘plami oilamizga ma’qul keldi, ta’mi tengsiz.',
    comment_ru: 'Отличный удобный сайт! Процесс заказа максимально прост. Сет шашлыков пришелся по вкусу всей семье, вкус безупречный.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=150&auto=format&fit=crop'
  }
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  uz: {
    // Nav & General UI
    brandName: 'Yalpiz',
    brandSlogan: 'Milliy va Zamonaviy Ta’m',
    navMenu: 'Menyu',
    navPromo: 'Aksiyalar',
    navAbout: 'Biz haqimizda',
    navBranches: 'Filiallar',
    navContact: 'Aloqa',
    orderBtn: 'Buyurtma berish',
    searchPlaceholder: 'Taomlarni qidirish...',
    popularBadge: 'Ommabop',
    currency: 'so‘m',
    available: 'Mavjud',
    outOfStock: 'Tugagan',
    addToCart: 'Savatga qo‘shish',
    cart: 'Savat',
    promoTitle: 'Aksiyalar va Maxsus Takliflar',
    promoSub: 'Yalpizdan eng mazali chegirmalar va to‘plamlar',
    reviewsTitle: 'Mijozlarimiz fikri',
    reviewsSub: 'Yalpiz mehmondo‘stligi va taomlarining haqiqiy bahosi',
    exploreMenu: 'Menyuni ko‘rish',
    learnMore: 'Batafsil',

    // Hero Section
    heroTitle: 'Milliy taomlar — eshigingizgacha',
    heroSub: 'An’anaviy retseptlar, eng yangi mahsulotlar va professional oshpazlardan mahorat mahsuli. Toshkent bo‘ylab 40 daqiqada issiq holda yetkazish.',
    marqueeFreeDelivery: 'Tez va ishonchli yetkazamiz',
    marqueeFreshDishes: 'Yangi yopilgan issiq nonlar',
    marqueeHotAndFresh: 'Issiq va sersuv kaboblar',
    marqueeTgOrder: 'Telegram bot orqali buyurtma',
    marqueeTradition: 'Asliy milliy ta’m',

    // Value Strip "Nega Yalpiz"
    whyTitle: 'Nega aynan Yalpiz?',
    whySub: 'Biz har bir taomni mehr bilan, milliy an’analarimiz va gigiyena qoidalariga rioya qilgan holda tayyorlaymiz',
    whyFreshTitle: '100% Yangi Mahsulotlar',
    whyFreshDesc: 'Har tong sarxil va tekshirilgan go‘sht va sabzavotlar tanlab olinadi.',
    whyFastTitle: 'Tezkor Yetkazib Berish',
    whyFastDesc: 'Maxsus termosumkalar yordamida taomlar issiq va o‘z ta’mida yetadi.',
    whyTasteTitle: 'Haqiqiy Milliy Lazzat',
    whyTasteDesc: 'Avloddan-avlodga o‘tib kelayotgan haqiqiy o‘zbekcha o‘tin oshi ta’mi.',
    whyAppTitle: 'Qulay Buyurtma Berish',
    whyAppDesc: 'Sayt, telefon yoki Telegram bot orqali 3 bosqichda oson buyurtma qiling.',

    // Category Selector
    cat_all: 'Barchasi',
    cat_osh: 'Osh va Palovlar',
    cat_mangal: 'Mangal va Shashliklar',
    cat_salatlar: 'Salatlar va Non',
    cat_ichimliklar: 'Yalpizli Ichimliklar',
    cat_setlar: 'Maxsus To‘plamlar (Set)',

    // About Section
    aboutTitle: 'Yalpiz — samimiy mehmondo‘stlik va milliy ta’m',
    aboutP1: '"Yalpiz" — Toshkentdagi oilaviy restoran bo‘lib, o‘zbek xalqining ko‘p asrlik mehmondo‘stlik madaniyatini zamonaviy talablar bilan uyg‘unlashtiradi. Restoran nomi xushbo‘y yalpiz sharafiga qo‘yilgan — u dasturxonimizning yengillik va tozalik timsolidir.',
    aboutP2: 'Menyuimiz boy va rang-barang: an’anaviy palov, sersuv shashlik va kaboblar, lag‘mon, tansiq salatlar hamda issiq tandir non. Portsiyalarimiz to‘kin, narxlarimiz esa hamyonbop — har bir mehmon to‘yib va mamnun qaytadi.',
    aboutP3: 'Har bir mehmonni iliq choy bilan kutib olamiz. Yalpizda oilaviy iliqlik va samimiy g‘amxo‘rlik qadrlanadi — tug‘ilgan kun, nikoh va boshqa tadbirlaringiz uchun ham eng yaxshi tanlov. Ikki filialimiz Mirobod va Shota Rustaveli ko‘chalarida sizni kutadi.',

    // Branches
    branchesTitle: 'Bizning Filiallarimiz',
    branchesSub: 'Sizga eng yaqin bo‘lgan restoranimizga tashrif buyuring yoki olib ketish uchun buyurtma bering',
    branchHours: 'Ish vaqti',
    branchPhone: 'Telefon',
    branchAddress: 'Manzil',
    branchDirections: 'Xaritadan ko‘rish',

    // Delivery Section
    deliveryTitle: 'Yetkazib berish va To‘lov',
    deliverySub: 'Sizga qulay va tezkor xizmat ko‘rsatish tizimimiz bilan tanishing',
    step1Title: 'Taomlarni tanlang',
    step1Desc: 'Menyudan xohlagan shoxona taomlarimizni savatga qo‘shing va tasdiqlang.',
    step2Title: 'Manzil va ma’lumotlar',
    step2Desc: 'Yetkazib berish manzilini kiriting yoki o‘zingizga qulay filialni tanlang.',
    step3Title: 'Issiqqina qabul qiling',
    step3Desc: 'Kuryerimiz 40 daqiqa ichida taomlarni termosumkada eshigingizgacha olib boradi.',
    paymentTitle: 'To‘lov usullari',
    paymentDesc: 'Siz buyurtmani o‘zingizga qulay tarzda to‘lashingiz mumkin:',
    payme: 'Payme orqali onlayn',
    click: 'Click orqali onlayn',
    cash: 'Kuryerga naqd yoki karta orqali',

    // Cart Drawer & Checkout
    cartTitle: 'Sizning savatingiz',
    cartEmpty: 'Savatingiz hozircha bo‘sh. Yoqimli taomlardan buyurtma bering!',
    cartSummary: 'Buyurtma tafsilotlari',
    cartTotal: 'Jami summa:',
    cartDeliveryCost: 'Yetkazib berish:',
    cartFree: 'Taxi haydovchiga naqd',
    checkoutTitle: 'Buyurtmani rasmiylashtirish',
    orderType: 'Buyurtma turi',
    typeDelivery: 'Yetkazib berish (Dostavka)',
    typePickup: 'Olib ketish (Samovivoz)',
    fullName: 'Ismingiz va familiyangiz',
    fullNamePlaceholder: 'Masalan: Alisher Karimov',
    phoneLabel: 'Telefon raqamingiz',
    phonePlaceholder: '99 123 45 67',
    addressLabel: 'Yetkazib berish manzili',
    addressPlaceholder: 'Tuman, ko‘cha, uy raqami, xonadon',
    selectBranch: 'Olib ketish filialini tanlang',
    paymentMethod: 'To‘lov turi',
    commentLabel: 'Kuryer yoki oshpaz uchun eslatma (ixtiyoriy)',
    commentPlaceholder: 'Masalan: Kirish kodi 45, oshga piyoz ko‘proq bo‘lsin',
    submitOrder: 'Buyurtmani tasdiqlash',
    orderProcessing: 'Buyurtma rasmiylashtirilmoqda...',
    orderSuccess: 'Sizning buyurtmangiz muvaffaqiyatli qabul qilindi!',
    orderSuccessSub: 'Tez orada operatorimiz siz bilan bog‘lanadi. Buyurtma raqamingiz: #YALPIZ-',
    backToMenu: 'Menyuga qaytish',
    qty: 'Soni',

    // Footer
    footerSlogan: 'O‘zbek milliy oshxonasining eng sara an’analari zamonaviy ko‘rinishda.',
    footerHours: 'Ish vaqti: Har kuni 09:00 dan 23:00 gacha',
    footerSocials: 'Biz ijtimoiy tarmoqlarda',
    footerBot: 'Telegram-bot orqali qulay va tez buyurtma bering',
    footerApp: 'Tez kunda Google Play va App Store platformalarida',
    footerRights: 'Barcha huquqlar himoyalangan.',
  },
  ru: {
    // Nav & General UI
    brandName: 'Yalpiz',
    brandSlogan: 'Национальный и современный вкус',
    navMenu: 'Меню',
    navPromo: 'Акции',
    navAbout: 'О нас',
    navBranches: 'Филиалы',
    navContact: 'Контакты',
    orderBtn: 'Заказать сейчас',
    searchPlaceholder: 'Поиск блюд...',
    popularBadge: 'Популярно',
    currency: 'сум',
    available: 'В наличии',
    outOfStock: 'Закончилось',
    addToCart: 'В корзину',
    cart: 'Корзина',
    promoTitle: 'Акции и Специальные Предложения',
    promoSub: 'Самые вкусные скидки и праздничные наборы от Yalpiz',
    reviewsTitle: 'Отзывы наших гостей',
    reviewsSub: 'Искренние слова о гостеприимстве и непревзойденном вкусе',
    exploreMenu: 'Смотреть меню',
    learnMore: 'Подробнее',

    // Hero Section
    heroTitle: 'Национальные блюда — прямо к вам домой',
    heroSub: 'Традиционные рецепты, свежайшие продукты и мастерство шеф-поваров. Горячая доставка по Ташкенту за 40 минут в термосумках.',
    marqueeFreeDelivery: 'Быстрая и надёжная доставка',
    marqueeFreshDishes: 'Горячие лепешки из тандыра',
    marqueeHotAndFresh: 'Горячие сочные шашлыки',
    marqueeTgOrder: 'Заказ через Telegram-бот',
    marqueeTradition: 'Оригинальный узбекский вкус',

    // Value Strip "Nega Yalpiz"
    whyTitle: 'Почему именно Yalpiz?',
    whySub: 'Мы готовим каждое блюдо с душой, строго следуя национальным традициям и стандартам гигиены',
    whyFreshTitle: '100% Свежие Продукты',
    whyFreshDesc: 'Каждое утро мы отбираем сертифицированное мясо и лучшие спелые овощи.',
    whyFastTitle: 'Быстрая Доставка',
    whyFastDesc: 'Специальные термосумки сохраняют идеальную температуру и аромат блюд.',
    whyTasteTitle: 'Аутентичный Вкус',
    whyTasteDesc: 'Настоящий плов на дровах по рецептам, передаваемым из поколения в поколение.',
    whyAppTitle: 'Удобный Заказ',
    whyAppDesc: 'Легко оформляйте заказ на сайте, по телефону или через Telegram-бот в 3 клика.',

    // Category Selector
    cat_all: 'Все блюда',
    cat_osh: 'Плов и Рис',
    cat_mangal: 'Мангал и Шашлыки',
    cat_salatlar: 'Салаты и Лепешки',
    cat_ichimliklar: 'Мятные Напитки',
    cat_setlar: 'Специальные Сеты',

    // About Section
    aboutTitle: 'Yalpiz — искреннее гостеприимство и национальный вкус',
    aboutP1: '«Yalpiz» — семейный ресторан в Ташкенте, объединяющий многовековую культуру узбекского гостеприимства с современными стандартами. Название происходит от ароматной мяты — символа свежести и лёгкости нашего дастархана.',
    aboutP2: 'Наше меню богато и разнообразно: традиционный плов, сочные шашлыки и кебабы, лагман, свежие салаты и горячие тандырные лепёшки. Порции щедрые, а цены доступные — каждый гость уходит сытым и довольным.',
    aboutP3: 'Каждого гостя мы встречаем чашкой ароматного чая. В Yalpiz ценят семейное тепло и искреннюю заботу — это отличный выбор для дня рождения, свадьбы и других торжеств. Два наших филиала ждут вас на улицах Миробод и Шота Руставели.',

    // Branches
    branchesTitle: 'Наши Филиалы',
    branchesSub: 'Посетите ближайший ресторан или оформите заказ для самовывоза',
    branchHours: 'Режим работы',
    branchPhone: 'Телефон',
    branchAddress: 'Адрес',
    branchDirections: 'Открыть на карте',

    // Delivery Section
    deliveryTitle: 'Доставка и Оплата',
    deliverySub: 'Ознакомьтесь с нашей удобной и быстрой системой сервиса',
    step1Title: 'Выберите блюда',
    step1Desc: 'Добавьте понравившиеся блюда из нашего меню в корзину и перейдите к оформлению.',
    step2Title: 'Укажите детали',
    step2Desc: 'Введите адрес доставки или выберите удобный для вас филиал самовывоза.',
    step3Title: 'Получите горячим',
    step3Desc: 'Наш курьер привезет ваш заказ в термосумке прямо к двери в течение 40 минут.',
    paymentTitle: 'Способы оплаты',
    paymentDesc: 'Вы можете оплатить свой заказ любым удобным для вас способом:',
    payme: 'Онлайн через Payme',
    click: 'Онлайн через Click',
    cash: 'Наличными или картой курьеру',

    // Cart Drawer & Checkout
    cartTitle: 'Ваша корзина',
    cartEmpty: 'Ваша корзина пуста. Добавьте в нее наши вкуснейшие блюда!',
    cartSummary: 'Детали заказа',
    cartTotal: 'Итоговая сумма:',
    cartDeliveryCost: 'Доставка:',
    cartFree: 'Такси водителю наличными',
    checkoutTitle: 'Оформление заказа',
    orderType: 'Способ получения',
    typeDelivery: 'Доставка на дом',
    typePickup: 'Самовывоз из филиала',
    fullName: 'Ваше имя и фамилия',
    fullNamePlaceholder: 'Например: Алишер Каримов',
    phoneLabel: 'Номер телефона',
    phonePlaceholder: '99 123 45 67',
    addressLabel: 'Адрес доставки',
    addressPlaceholder: 'Район, улица, номер дома, квартира',
    selectBranch: 'Выберите филиал для самовывоза',
    paymentMethod: 'Способ оплаты',
    commentLabel: 'Комментарий к заказу (необязательно)',
    commentPlaceholder: 'Например: Вход со двора, код домофона 45, плов без лука',
    submitOrder: 'Подтвердить заказ',
    orderProcessing: 'Оформление заказа...',
    orderSuccess: 'Ваш заказ успешно принят!',
    orderSuccessSub: 'В ближайшее время с вами свяжется оператор для подтверждения. Номер вашего заказа: #YALPIZ-',
    backToMenu: 'Вернуться в меню',
    qty: 'Кол-во',

    // Footer
    footerSlogan: 'Лучшие традиции узбекской национальной кухни в современном и стильном исполнении.',
    footerHours: 'Время работы: Ежедневно с 09:00 до 23:00',
    footerSocials: 'Мы в социальных сетях',
    footerBot: 'Заказывайте удобно и быстро через Telegram-бот',
    footerApp: 'Скоро в Google Play и App Store',
    footerRights: 'Все права защищены.',
  }
};
